// Auto-generated by OpenLane
module gpio_vector(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  inout[15:0] PIN_DATA,
  input clk,
  input reset,
  input Enable,
  input[15:0] Function,
  input[15:0] Data_out,
  input[15:0] Pin_Change_Mask,
  input[1:0] Int_Mask,
  output[15:0] Data_in,
  output[15:0] Pin_out,
  output IRQ_PIN_CHANGE,
  output[1:0] IRQ_INT
);
endmodule
